apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dockerregistrykeyName" .}}
  # namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}